### ISSUE TITLE
config node is blocking, while json file is incorrect

### ISSUE THREAD

**Issue by Trust-Point** [FHatCSW/node-red-contrib-ejbca#1]
If the json config file is incorrect the node is blocking the whole node red. 
After restart the config node couldn't open.

**Comment by FHatCSW** [comment]
With the actual [commit](https://github.com/FHatCSW/node-red-contrib-ejbca/commit/55d7833a586bd0a5afb1f634ed51c88b221ed012) there is a validator which checks if all arguments are existent and have the right format

Example for bad config:
<img width="479" alt="image" src="https://github.com/FHatCSW/node-red-contrib-ejbca/assets/99396351/897ecda0-4bde-4602-ad3b-52863e07684e">


Example for good config:
<img width="479" alt="image" src="https://github.com/FHatCSW/node-red-contrib-ejbca/assets/99396351/50a74a91-3208-4fa3-ae57-e09743a36458">
